defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.dashboard]
    address = ":8080"
  [entryPoints.http]
    address = ":80"

[api]
entrypoint="dashboard"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.local.com"
watch = true
network = "webproxy"
swarmModeRefreshSeconds = 15